// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StaffManagement.API.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string StaffId { get; set; }

    public string FullName { get; set; }

    public DateOnly? BirthDay { get; set; }

    public int? Gender { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}